### ISSUE TITLE
Selected Line Color overrides bracket matching color

### ISSUE THREAD

**Issue by tobbi007** [classikd/notepad-plus-plus-syntax#5]
Wanted behaviour:
![wanted](https://user-images.githubusercontent.com/509232/48348618-28d53b00-e682-11e8-8d6d-fd1a1ba84a76.JPG)

Actual behaviour:
![actual](https://user-images.githubusercontent.com/509232/48348672-4bffea80-e682-11e8-94a6-14b59a39e47c.JPG)

Woraround:
Added transparency to colors.less 
@selected-line: rgba(232,232,255,0.5);

**Comment by classikd** [comment]
Ohhh nice ! Thanks for that :) I am going to publish a new version for all users.
Unfortunately i noticed the problem still occurs when php code is in html attributes :
![line](https://user-images.githubusercontent.com/5224312/48372862-35788400-e6c0-11e8-9536-fbf7eb0ffe6f.JPG)
but i think atom is the problem we cannot solve that, there is the same behavior in official themes.

**Comment by tobbi007** [comment]
Ohh nice find with the inline php block. Didn't find that one. But usually the inline php blocks are pretty short so this doesn't bother me too much.
Thank you for releasing a new version for everyone :)
