### ISSUE TITLE
Color coded <script> <php>

### ISSUE THREAD

**Issue by fallenruby** [classikd/notepad-plus-plus-syntax#6]
The theme is almost perfect. The thing I miss the most is the background color for the `<script>` tag and `<?php>`.

![notepada](https://user-images.githubusercontent.com/9852958/51477071-93dc7580-1d87-11e9-9ab5-867c3d1f313d.JPG)

Can we do something about that?
Thank you.

**Comment by classikd** [comment]
Hey,
Nice find I had never noticed those missing colors !
I tried to add them but unfortunately I think we can't do better than that:
![atom-npp-line-bg](https://user-images.githubusercontent.com/5224312/51562690-b6a38280-1e8a-11e9-841c-1d4cba167883.jpg)
The classes we need to target the code are not on the full width element (.line) 
:S
