### ISSUE TITLE
An error in the

### ISSUE THREAD

**Issue by linjialiang** [classikd/notepad-plus-plus-syntax#7]
![图片](https://user-images.githubusercontent.com/8848263/55445599-b93ef880-55ee-11e9-8fbc-0aa3ad61d955.png)

**Comment by classikd** [comment]
Hello linjialiang,

What is that ?  I don't think this is related to the theme =D

**Comment by linjialiang** [comment]
> Sorry, I made a mistake, this should be the problem of ide

**Comment by classikd** [comment]
No problem =)
