### ISSUE TITLE
Wrong coloring on constants & missing functions

### ISSUE THREAD

**Issue by MrSvenson** [classikd/notepad-plus-plus-syntax#8]
Hey, thanks for a great theme :)

Take a look at the picture below. Is this something that can be corrected?

![image](https://user-images.githubusercontent.com/39689292/67888392-4fb7a600-fb4d-11e9-8bb5-2ed66c5ff6d2.png)

**Comment by classikd** [comment]
Hello !
I'm going to take a look.
But why the hello string is blue for you, it's strange. 
Did you select the correct grammar (php) for this file ?

**Comment by classikd** [comment]
I've fixed the wrong color for php functions, thanks for reporting that. PHP users will appreciate.
On the other hand, for those constants we cannot improve anything at the moment because it would affect some other stuff..
I will release a new version soon.

Edit: Version 0.2.12 released

**Comment by MrSvenson** [comment]
Big improvement when reading through chunks of PHP code. Thanks a lot! The text being blue was due to me fiddling around with the colors myself trying to sort this out as it made my work incredibly annoying.
